name: A4 Workflow
env:
    API_URL: ${{secrets.API_URL}}
on:
    push:
        branches:
            - main
            - "*Assignment*"
        paths:
            - "wordle-web/**"
            - "**/azure-static-web*"
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main
    workflow_dispatch:

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        name: Build and Deploy Job

        steps:
            - uses: actions/checkout@v2
              name: Checkout source
              with:
                  submodules: true
            - uses: actions/setup-node@v2
              name: Node Setup
              with:
                  node-version: "14"
            - run: npm i
              name: Run NPM install
              working-directory: ./wordle-web
            - run: npm run test
              name: Run npm tests
              working-directory: ./wordle-web
            - run: npm run generate
              name: Generate nuxt app
              working-directory: ./wordle-web
            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: "upload"
                  ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_location: "/wordle-web/dist" # App source code path
                  api_location: "" # Api source code path - optional
                  output_location: "dist" # Built app content directory - optional
                  skip_app_build: true
                  skip_api_build: true
                  ###### End of Repository/Build Configurations ######

    deploy:
        runs-on: windows-latest
        needs: build_and_deploy_job
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: .net-app

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "WordleApiClassDavid"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.API_AZUREAPPSERVICE_PUBLISHPROFILE }}
                  package: .
